export const slides = [
    {
        id:1,
        src:"public/images/1.jpg",
    },{
        id:2,
        src:"public/images/2.jpg",
    },{
        id:3,
        src:"public/images/3.jpg",
    },{
        id:4,
        src:"public/images/4.jpg",
    },{
        id:5,
        src:"public/images/5.jpg",
    },{
        id:6,
        src:"public/images/6.jpg",
    },{
        id:7,
        src:"public/images/7.jpg",
    },{
        id:8,
        src:"public/images/8.jpg",
    },{
        id:9,
        src:"public/images/9.jpg",
    },{
        id:10,
        src:"public/images/10.jpg",
    },{
        id:11,
        src:"public/images/11.jpg",
    },{
        id:12,
        src:"public/images/12.jpg",
    },{
        id:13,
        src:"public/images/herobg1.jpg",
    },{
        id:14,
        src:"public/images/herobg2.jpg",
    },{
        id:15,
        src:"public/images/15.jpeg",
    },
]